name: "tool-reading"
tool_command: "python"
args:
  - "-m"
  - "src.tool.mcp_servers.reading_mcp_server"
env:
  SERPER_API_KEY: "${oc.env:SERPER_API_KEY,}" 
  JINA_API_KEY: "${oc.env:JINA_API_KEY,}"
  http_proxy: "${oc.env:http_proxy,}"
  https_proxy: "${oc.env:https_proxy,}"
  no_proxy: "${oc.env:no_proxy,}"  