name: gitleaks

on:
  pull_request:
    branches: [ "main" ]
  push:
  # workflow_dispatch:
  # schedule:
  #   - cron: "0 4 * * *" # run once a day at 4 AM

permissions:
  contents: read
  # maybe needed by pull_request
  pull-requests: write

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      # see https://github.com/actions/checkout/issues/20#issuecomment-524521113
      # this is a hack to reduce the number of commits to scan
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
          ref: ${{ github.ref }}
      - uses: gitleaks/gitleaks-action@v2
        # see https://github.com/gitleaks/gitleaks-action?tab=readme-ov-file#environment-variables
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.
          # optional config
          GITLEAKS_NOTIFY_USER_LIST: "@MiroMindAI"
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_ENABLE_COMMENTS: true